# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sgpt < Formula
  desc "SGPT is a command-line tool that provides a convenient way to interact with OpenAI models,
enabling users to run queries, generate shell commands, produce code,
and create images from text directly from the terminal."
  homepage ""
  version "2.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tbckr/sgpt/releases/download/v2.6.1/sgpt_Darwin_x86_64.tar.gz"
      sha256 "7f09b63c204d5588a2e0d9a2e739e5ae5e216d53227c41f66c7c795f559a9ccd"

      def install
        bin.install "sgpt"
        bash_completion.install "completions/sgpt.bash" => "sgpt"
        zsh_completion.install "completions/sgpt.zsh" => "_sgpt"
        fish_completion.install "completions/sgpt.fish"
        man1.install "manpages/sgpt.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tbckr/sgpt/releases/download/v2.6.1/sgpt_Darwin_arm64.tar.gz"
      sha256 "1a157d335ece22d4c3e7c3dad031119b56ec9e81c93862c0891b6183f2cdafd2"

      def install
        bin.install "sgpt"
        bash_completion.install "completions/sgpt.bash" => "sgpt"
        zsh_completion.install "completions/sgpt.zsh" => "_sgpt"
        fish_completion.install "completions/sgpt.fish"
        man1.install "manpages/sgpt.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tbckr/sgpt/releases/download/v2.6.1/sgpt_Linux_arm64.tar.gz"
      sha256 "cab50a34e7c16f114c429756a7b5e35bba41d8bf0f8c2f8258dfd4c308de5f4b"

      def install
        bin.install "sgpt"
        bash_completion.install "completions/sgpt.bash" => "sgpt"
        zsh_completion.install "completions/sgpt.zsh" => "_sgpt"
        fish_completion.install "completions/sgpt.fish"
        man1.install "manpages/sgpt.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tbckr/sgpt/releases/download/v2.6.1/sgpt_Linux_x86_64.tar.gz"
      sha256 "59332da020d6fddb7c301afb58b9158edf0fc1b8b647135612601cc6a190f3b9"

      def install
        bin.install "sgpt"
        bash_completion.install "completions/sgpt.bash" => "sgpt"
        zsh_completion.install "completions/sgpt.zsh" => "_sgpt"
        fish_completion.install "completions/sgpt.fish"
        man1.install "manpages/sgpt.1.gz"
      end
    end
  end
end
